#pragma once

#include <QtCore/QLoggingCategory>

// === app ===
Q_DECLARE_LOGGING_CATEGORY(lcApp)

// === core.* ===
Q_DECLARE_LOGGING_CATEGORY(lcCoreProtocol)
Q_DECLARE_LOGGING_CATEGORY(lcCoreThreading)
Q_DECLARE_LOGGING_CATEGORY(lcCoreConfig)
Q_DECLARE_LOGGING_CATEGORY(lcClipboard)
Q_DECLARE_LOGGING_CATEGORY(lcTransfer)

// === server.* ===
Q_DECLARE_LOGGING_CATEGORY(lcServer)
Q_DECLARE_LOGGING_CATEGORY(lcServerNetwork)
Q_DECLARE_LOGGING_CATEGORY(lcServerCapture)
Q_DECLARE_LOGGING_CATEGORY(lcServerCaptureDxgi)
Q_DECLARE_LOGGING_CATEGORY(lcServerEncode)
Q_DECLARE_LOGGING_CATEGORY(lcServerQueue)
Q_DECLARE_LOGGING_CATEGORY(lcServerClientHandler)
Q_DECLARE_LOGGING_CATEGORY(lcServerInput)

// === client.* ===
Q_DECLARE_LOGGING_CATEGORY(lcClient)
Q_DECLARE_LOGGING_CATEGORY(lcClientSession)
Q_DECLARE_LOGGING_CATEGORY(lcClientSessionDecode)
Q_DECLARE_LOGGING_CATEGORY(lcClientSessionProtocol)
Q_DECLARE_LOGGING_CATEGORY(lcClientGL)
Q_DECLARE_LOGGING_CATEGORY(lcClientRemoteWindow)

// === ui.* ===
Q_DECLARE_LOGGING_CATEGORY(lcUI)
Q_DECLARE_LOGGING_CATEGORY(lcUIMainWindow)
Q_DECLARE_LOGGING_CATEGORY(lcUISettingsDialog)

// === test.* ===
Q_DECLARE_LOGGING_CATEGORY(lcTest)
Q_DECLARE_LOGGING_CATEGORY(lcTestScreenCapture)
Q_DECLARE_LOGGING_CATEGORY(lcTestScreenCaptureIntegration)
Q_DECLARE_LOGGING_CATEGORY(lcTestClientHandler)
Q_DECLARE_LOGGING_CATEGORY(lcTestProducerConsumer)
